title: Wheelhouse Editorial
description: Editing & content leadership for authors, publishers, and product teams.
baseurl: "" 
url: ""
author:
  name: Gillian McGarvey
  email: gillian@wheelhouseeditorial.com
permalink: /:title/
markdown: kramdown
exclude:
  - node_modules
  - README.md
  - package.json
  - package-lock.json
